import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import NavBar from "../components/NavBar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container flex flex-col p-4 mx-auto max-w-4xl motion-safe:animate-fade-in sm:p-8">
    <main className="flex-grow mb-16 min-h-screen sm:motion-safe:animate-slide-down-fade">
    <section className="space-y-8">
    <div className="py-[10vh] prose prose-invert md:py-[20vh]">
    <p className="lead"><b>Ryann Ferreira</b></p>
    <h1 className="text-4xl">
    Criando experiências na Web usando tecnologias modernas de Frontend e Backend
    </h1>
    <p className="my-4">Desenvolvedor Full Stack na Primata e contribuidor de projetos open-source como o Gnome</p>
    <p className="my-4">Para entrar em contato use o email: <a href="mailto:ryannnkl@gmail.com" className="link">ryannnkl@gmail.com</a> ou entre em contato pelo instagram: <a tagert="_blank" href="https://instagram.com/ryann_ferreira_" className="link">ryann_ferreira_</a></p>
    </div>
    </section>
    </main>
    </div>

    <NavBar /> 
    </div>
  )
}

export default Home
